# Generated by Django 5.0.2 on 2024-02-27 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='언체크하면 settings.py에서 설성한 기본 계정으로 발송됩니다.', verbose_name='Active')),
                ('database', models.CharField(default='default', help_text='이메일 발송에 사용될 데이터베이스명입니다.', max_length=30, verbose_name='데이터베이스 이름')),
                ('host', models.CharField(default='localhost', help_text='localhost', max_length=50, verbose_name='이메일 발송 호스트')),
                ('send_method', models.CharField(choices=[('smtp', '사용자 지정 SMTP 서버'), ('gmail', 'Gmail'), ('outlook', 'Outlook')], default='smtp', max_length=15, verbose_name='발송 방법')),
                ('user', models.CharField(default='', max_length=70, verbose_name='이메일')),
                ('api_client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API CLIENT ID')),
                ('api_client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='API CLIENT SECRET')),
                ('api_refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='API REFRESH TOKEN')),
                ('security_protocol', models.CharField(blank=True, choices=[('tls', 'TLS'), ('ssl', 'SSL')], max_length=15, null=True, verbose_name='이메일 발송 방법')),
                ('port', models.PositiveSmallIntegerField(blank=True, help_text=25, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='비밀번호')),
                ('from_email', models.CharField(blank=True, max_length=120, null=True, verbose_name='보내일 메일')),
                ('reply_to', models.CharField(blank=True, max_length=120, null=True, verbose_name='반송 메일')),
                ('cc', models.CharField(blank=True, help_text='컴마로 구분합니다.', max_length=220, null=True, verbose_name='참조')),
                ('bcc', models.CharField(blank=True, help_text='컴마로 구분합니다.', max_length=220, null=True, verbose_name='숨은 참조')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Email Host',
                'verbose_name_plural': 'Email Host',
                'db_table': 'celeryemailbackend_emailhost',
            },
        ),
        migrations.CreateModel(
            name='SendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='분류')),
                ('recipients', models.CharField(blank=True, max_length=1200, null=True, verbose_name='수신자들')),
                ('subject', models.CharField(max_length=200, verbose_name='타이틀')),
                ('body', models.TextField(blank=True, null=True, verbose_name='본문')),
                ('arranged_time', models.DateTimeField(auto_now_add=True, verbose_name='예약시간')),
                ('sent_time', models.DateTimeField(blank=True, null=True, verbose_name='발송시간')),
                ('success', models.BooleanField(null=True)),
                ('message_id', models.UUIDField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Sending History',
                'verbose_name_plural': 'Email Sending History',
                'db_table': 'celeryemailbackend_emailsendhistory',
            },
        ),
    ]
