# Generated by Django 5.0.2 on 2024-02-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0003_alter_emailhost_api_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], max_length=40, unique=True, verbose_name='Provider Name')),
                ('client_id', models.CharField(max_length=255, verbose_name='CLIENT_ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='CLIENT_SECRET')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Provider',
                'db_table': 'oauthemailbackend_provider',
            },
        ),
        migrations.AddField(
            model_name='emailhost',
            name='provider',
            field=models.CharField(blank=True, choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], max_length=20, null=True, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='emailhost',
            name='send_method',
            field=models.CharField(choices=[('smtp', 'SMTP 서버'), ('api', 'OAuth API')], default='smtp', max_length=15, verbose_name='발송 방법'),
        ),
    ]
