# Generated by Django 5.0.2 on 2024-02-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0004_provider_emailhost_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailhost',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth_emailbackend.provider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='emailhost',
            name='send_method',
            field=models.CharField(choices=[('smtp', '사용자 지정 SMTP 서버'), ('api', 'OAuth 이메일 API')], default='smtp', max_length=15, verbose_name='발송 방법'),
        ),
    ]
