# Generated by Django 5.0.2 on 2024-03-06 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0006_provider_created_provider_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Gmail', 'Gmail'), ('Outlook', 'Outlook')], max_length=40, unique=True, verbose_name='Provider Name')),
                ('client_id', models.CharField(max_length=255, verbose_name='CLIENT_ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='CLIENT_SECRET')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Provider',
                'db_table': 'oauthemailbackend_oauthapi',
            },
        ),
        migrations.RemoveField(
            model_name='emailhost',
            name='provider',
        ),
        migrations.AddField(
            model_name='emailhost',
            name='oauthapi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth_emailbackend.oauthapi', verbose_name='OAuth API'),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
