# Generated by Django 5.0.2 on 2024-03-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0007_oauthapi_remove_emailhost_provider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthapi',
            options={'verbose_name': 'OAuth API', 'verbose_name_plural': 'OAuth API'},
        ),
        migrations.RemoveField(
            model_name='oauthapi',
            name='name',
        ),
        migrations.AddField(
            model_name='oauthapi',
            name='provider',
            field=models.CharField(default='1', max_length=140, unique=True, verbose_name='Provider'),
            preserve_default=False,
        ),
    ]
