# Generated by Django 5.0.2 on 2024-03-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0008_alter_oauthapi_options_remove_oauthapi_name_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthapi',
            options={'verbose_name': '  OAuth API', 'verbose_name_plural': '  OAuth API'},
        ),
        migrations.CreateModel(
            name='EmailClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='언체크하면 settings.py에서 설성한 기본 계정으로 발송됩니다.', verbose_name='Active')),
                ('database', models.CharField(default='default', help_text='이메일 발송에 사용될 데이터베이스명입니다.', max_length=30, verbose_name='데이터베이스 이름')),
                ('send_method', models.CharField(choices=[('smtp', '사용자 지정 SMTP 서버'), ('api', 'OAuth 이메일 API')], default='smtp', max_length=15, verbose_name='발송 방법')),
                ('user', models.CharField(default='', max_length=70, verbose_name='이메일')),
                ('api_token', models.TextField(blank=True, null=True, verbose_name='API TOKEN')),
                ('smtp_host', models.CharField(blank=True, max_length=50, null=True, verbose_name='SMTP 발송 호스트')),
                ('security_protocol', models.CharField(blank=True, choices=[('tls', 'TLS'), ('ssl', 'SSL')], max_length=15, null=True, verbose_name='보안 프로토콜')),
                ('port', models.PositiveSmallIntegerField(blank=True, help_text=25, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='비밀번호')),
                ('reply_to', models.CharField(blank=True, max_length=120, null=True, verbose_name='반송 메일')),
                ('cc', models.CharField(blank=True, help_text='컴마로 구분합니다.', max_length=220, null=True, verbose_name='참조')),
                ('bcc', models.CharField(blank=True, help_text='컴마로 구분합니다.', max_length=220, null=True, verbose_name='숨은 참조')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('oauthapi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth_emailbackend.oauthapi', verbose_name='OAuth API')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Email Client',
                'verbose_name_plural': 'Email Client',
                'db_table': 'oauthemailbackend_emailclient',
            },
        ),
        migrations.DeleteModel(
            name='EmailHost',
        ),
    ]
