# Generated by Django 5.0.2 on 2024-03-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0011_remove_emailclient_api_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthapi',
            name='secret_file',
        ),
        migrations.AddField(
            model_name='oauthapi',
            name='client_config',
            field=models.JSONField(help_text='CLIENT_ID, CLIENT_SECRET이 포함된 보안 비밀번호 json 파일', null=True, verbose_name='클라이언트 설정(JSON)'),
        ),
    ]
