# Generated by Django 5.0.2 on 2024-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0012_remove_oauthapi_secret_file_oauthapi_client_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthapi',
            options={'verbose_name': '   OAuth API', 'verbose_name_plural': '   OAuth API'},
        ),
        migrations.AlterField(
            model_name='emailclient',
            name='next_token_refresh_date',
            field=models.DateTimeField(blank=True, help_text='갱신일 이전에 자동 갱신 시도합니다.', null=True, verbose_name='다음 Token 갱신일'),
        ),
    ]
