# Generated by Django 5.0.2 on 2024-03-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0013_alter_oauthapi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailclient',
            name='user',
            field=models.EmailField(max_length=254, verbose_name='사용자 이메일'),
        ),
    ]
