# Generated by Django 5.0.2 on 2024-03-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0014_alter_emailclient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailclient',
            old_name='next_token_refresh_date',
            new_name='token_expiry',
        ),
    ]
