# Generated by Django 5.0.2 on 2024-03-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0015_rename_next_token_refresh_date_emailclient_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailclient',
            name='user',
        ),
        migrations.AddField(
            model_name='emailclient',
            name='api_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='API 계정 이메일'),
        ),
        migrations.AddField(
            model_name='emailclient',
            name='smtp_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='SMTP 계정 이메일'),
        ),
    ]
