# Generated by Django 5.0.2 on 2024-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0017_rename_database_emailclient_using'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclient',
            name='debug',
            field=models.BooleanField(default=True, help_text='로그를 작성합니다.', verbose_name='디버그'),
        ),
    ]
