# Generated by Django 5.0.2 on 2024-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0018_emailclient_debug'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclient',
            name='sender_name',
            field=models.CharField(max_length=20, null=True, verbose_name='보내는 사람 이름'),
        ),
    ]
