# Generated by Django 5.0.2 on 2024-04-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0021_remove_sendhistory_id_alter_sendhistory_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendhistory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sendhistory',
            name='user',
        ),
    ]
