# Generated by Django 5.0.2 on 2024-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0022_remove_sendhistory_category_remove_sendhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
