# Generated by Django 5.0.2 on 2024-04-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0023_sendhistory_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendhistory',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
