# Generated by Django 5.0.2 on 2024-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0024_sendhistory_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendhistory',
            name='success',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
