# Generated by Django 5.0.2 on 2024-04-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_emailbackend', '0025_alter_sendhistory_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sendhistory',
            name='message_id',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
